app/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

app_name = "api"

router = DefaultRouter()

urlpatterns = [
    path("", include(router.urls)),
]

app/db_manager/urls.py
from django.urls import path

from db_manager import views

app_name = 'db_manager'

urlpatterns = [
    path("db-manager", views.db_manager, name="db-manager"),
    path("db-upload", views.db_upload, name="db-upload"),
    path("db-download", views.db_download, name="db-download"),

]

app/portal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import TemplateView
from core.views import IndexTemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('auth/', include('dj_rest_auth.urls')),
    path('auth/registration/', include('dj_rest_auth.registration.urls')),
    path('auth/', include('user.urls')),
    path('api/', include('api.urls')),
    path('api/', include('xrp_ledger.urls')),
    path('db/', include('db_manager.urls')),
    re_path(r"^.*$", IndexTemplateView.as_view(), name="entry-point")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/db_manager/views.py
import pandas as pd
from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import render


from db_manager.data_validation import dataset_check


@user_passes_test(lambda u: u.is_superuser)
def db_manager(request):
    """Basic DB Manager dashboard"""

    return render(request, "db-manager.html")


@user_passes_test(lambda u: u.is_superuser)
def db_upload(request):
    """DB Manager for uploads"""

    return render(request, "db-upload.html")


@user_passes_test(lambda u: u.is_superuser)
def db_download(request):
    """DB Manager for downloads"""

    return render(request, "db-download.html")


@user_passes_test(lambda u: u.is_superuser)
def dataset_upload(request, dataset_type):
    """Bulk dataset upload to database"""
    meta = []
    dataset_errors = []
    report = dict()

    # To check if foreign key field exists before uploading
    CATEGORIES = set(list(CategoryModel.objects.all().values_list('category', flat=True)))

    if request.method == "POST":
        csv_file = request.FILES["csv_file"]
        filename = csv_file.name
        if not csv_file.name.endswith('.csv'):
            critical_error = "Incorrect file format. Please upload CSV file"
            return render(request, "upload.html",
                {"critical_error": critical_error, })
        data = pd.read_csv(csv_file, encoding="utf-8-sig")

        # Generate meta and error report
        meta, dataset_errors = dataset_check(data, dataset_type,
            categories=CATEGORIES
        )

        if len(meta) < 10:
            meta_1 = meta[:4]
            meta_2 = meta[4:8]
            meta_3 = meta[8:]
        else:
            meta_1 = meta[:8]
            meta_2 = meta[8:16]
            meta_3 = meta[16:]

        # No error has been found
        if len(dataset_errors) == 0:
            # try:
            # if dataset_type == "categories":
            #     report = data_upload.dataset_category_upload(data)

            # except:
            #     critical_error = "Dataset upload wasn't successful due to error"
            #     return render(request, "upload.html",
            #                   {"critical_error": critical_error, })

            upload_report = report
            return render(request, "upload.html",
                {"meta_1": meta_1, "meta_2": meta_2, "meta_3": meta_3, "upload_report": upload_report, "filename": filename,
                 "d_type": dataset_type})

        else:
            return render(request, "upload.html",
                {"meta_1": meta_1, "meta_2": meta_2, "meta_3": meta_3,
                 "dataset_errors": dataset_errors,
                 "filename": filename, "d_type": dataset_type})

    return render(request, "upload.html", {"d_type": dataset_type})

app/db_manager/templates/db-download.html
{% extends "base.html" %}
{% load static %}


{% block content %}
<div class="dashboard-db-manager">
  <div class="row row-cards">
    <div class="row text-start row-back">
      <a href="{% url 'db_manager:db-manager' %}">
        <i class="fas fa-chevron-left"></i> Back To DB Manager
      </a>
    </div>
    <div class="card card-description">
      {% if user.is_superuser %}
      {% endif %}
    </div>
  </div>
</div>

{% endblock %}

app/db_manager/templates/db-manager.html
{% extends "base.html" %}
{% load static %}



{% block content %}
<div class="dashboard-db-manager">
  <div class="row row-cards">
    <div class="row text-start row-back">
      <a href="/">
        <i class="fas fa-chevron-left"></i> Back To Homepage
      </a>
    </div>
    <div class="card card-description">
      {% if user.is_superuser %}
      <div class="row">
        <div class=" col col-12 col-sm-12 col-md-11 col-lg-2 plain-element">
          <span class="section-header ">Common</span>

        </div>
      </div>

      <div class="row plain-element">
        <div class=" col col-12 col-sm-12 col-md-6 col-lg-3 plain-element">
          <div class="row plain-element text-start">
            <div class="input-field col col-sm-9 col-form">
              <a href="{% url 'db_manager:db-upload' %}">
                <div class="card menu-card">
                  <h5><i class="fas fa-chevron-right"></i> DB Upload </h5>
                </div>
              </a>
            </div>
            <div class="input-field col col-sm-9 col-form">
              <a href="{% url 'db_manager:db-download' %}">
                <div class="card menu-card">
                  <h5><i class="fas fa-chevron-right"></i> DB Download </h5>
                </div>
              </a>
            </div>

          </div>
        </div>
      </div>

      {% endif %}
    </div>
  </div>
</div>


{% endblock %}

app/db_manager/templates/db-upload.html
{% extends "base.html" %}
{% load static %}


{% block content %}
<div class="dashboard-db-manager">
  <div class="row row-cards">
    <div class="row text-start row-back">
      <a href="{% url 'db_manager:db-manager' %}">
        <i class="fas fa-chevron-left"></i> Back To DB Manager
      </a>
    </div>
    <div class="card card-description">
      {% if user.is_superuser %}
      <div class="row plain-element">
        <div class=" col col-12 col-sm-12 col-md-8 col-lg-2 plain-element">
          <div class=" col col-12 col-sm-12 col-md-8 col-lg-11 plain-element">
            <span class="section-header ">Common</span>

          </div>
          <div class="row plain-element text-start">
            <div class="input-field  col col-12 col-sm-12 col-form">
              <a href="{% url 'db_manager:dataset-upload' dataset_type='categories' %}">
                <div class="card menu-card">
                  <h5><i class="fas fa-chevron-right"></i> Category Upload </h5>
                </div>
              </a>
            </div>
            <div class="input-field  col col-12 col-sm-12 col-form">
              <a href="{% url 'db_manager:dataset-upload' dataset_type='subcategories' %}">
                <div class="card menu-card">
                  <h5><i class="fas fa-chevron-right"></i> Subcategory Upload </h5>
                </div>
              </a>
            </div>
            <div class="input-field  col col-12 col-sm-12 col-form">
              <a href="{% url 'db_manager:dataset-upload' dataset_type='items' %}">
                <div class="card menu-card">
                  <h5><i class="fas fa-chevron-right"></i> Item Upload </h5>
                </div>
              </a>
            </div>
            <div class="input-field  col col-12 col-sm-12 col-form">
              <a href="{% url 'db_manager:dataset-upload' dataset_type='medical supplies' %}">
                <div class="card menu-card">
                  <h5><i class="fas fa-chevron-right"></i> Medical Supplies </h5>
                </div>
              </a>
            </div>
            <div class="input-field  col col-12 col-sm-12 col-form">
              <a href="{% url 'db_manager:dataset-upload' dataset_type='expiry dates' %}">
                <div class="card menu-card">
                  <h5><i class="fas fa-chevron-right"></i> Expiry Dates </h5>
                </div>
              </a>
            </div>

          </div>

        </div>
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/db_manager/templates/full-download.html
{% extends "base.html" %}
{% load static %}


{% block content %}
<div class="dashboard-db-manager">
  <div class="row row-cards">
    <div class="row text-start row-back">
      <a href="{% url 'db_manager:db-download' %}">
        <i class="fas fa-chevron-left"></i> Back To DB Download
      </a>
    </div>
    <div class="card card-description">

    </div>
  </div>
</div>

{% endblock %}

app/db_manager/templates/upload.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="dashboard-db-manager">
  <div class="row row-cards">
    <div class="row text-start row-back">
      <a href="{% url 'db_manager:db-upload' %}">
        <i class="fas fa-chevron-left"></i> Back To DB Upload
      </a>
    </div>
    <div class="card card-description">
      <div class="row plain-element">
        <div class=" col col-12 col-sm-12 col-md-4 col-lg-3 plain-element">
          <div class="row plain-element text-start">
            <div class="input-field col col-sm-9 col-form">
              <h4> Upload {{ d_type }} </h4>
            </div>
          </div>
          <form action="{% url 'db_manager:dataset-upload' dataset_type=d_type  %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}


            <div class="row plain-element text-start">
              <input class="form-control file-input" type="file" name="csv_file" id="csv_file" accept=".csv" required="True">
            </div>

            <div class="row plain-element text-start">
              <div class="input-field col col-sm-9 col-form">
                <button type="submit" class="btn btn-submit">
                  <i class="fas fa-file-csv"></i>&nbsp; Upload CSV File
                </button>
              </div>
            </div>
          </form>

          <div class="row plain-element">
            <div class="input-field col col-sm-9 col-form">
              {% if critical_error %}
              <h6 class="error">{{ critical_error }}</h6>
              {% endif %}
              {% if upload_report %}
              <div class="row plain-element text-start">
                <br>
                <h4> Dataset Report:</h4>

                <p class="">New: {{ upload_report.new }}</p>
                <p class="">Updates: {{ upload_report.updates }}</p>
                <p class="">Errors: {{ upload_report.errors }}</p>
                <p>Upload Errors:</p>
                {% for element in upload_report.upload_errors %}
                <ol><p class="error">{{element}}</p></ol>
                {% endfor %}
              </div>
              {% endif %}
              {% if dataset_errors %}
              <div class="row plain-element text-start">
                <h4> Dataset Issues:</h4>
              </div>
              {% for error in dataset_errors %}
              <div class="row plain-element text-start">
                <h6 class="error">{{ error }}</h6>
              </div>
              {% endfor %}
              {% endif %}
            </div>
          </div>
        </div>

        <div class=" col col-12 col-sm-12 col-md-6 col-lg-9 plain-element">
          {% if meta_1 %}
          <div class="row plain-element text-start">
            <div class="input-field col col-sm-10 col-form">
              <h4> {{ filename }} Summary:</h4>
            </div>
          </div>
          <div class="row plain-element">
          <div class=" col col-12 col-sm-12 col-md-12 col-lg-4 plain-element">
            {% for element in meta_1 %}
            <div class="row plain-element text-start">
              <h6>{{element.name}}</h6>
            </div>
            <div class="row plain-element text-start">
              <table class="table-overview">
                {% for key, value in element.items %}
                {% if key != "name" %}
                <tr>
                  <td class="td-category">{{ key }}</td>
                  <td>{{ value | truncatechars:100 }}</td>
                </tr>
                {% endif %}
                {% endfor %}
              </table>
            </div>
            {% endfor %}
          </div>
          <div class=" col col-12 col-sm-12 col-md-12 col-lg-4 plain-element">
            {% for element in meta_2 %}
            <div class="row plain-element text-start">
              <h6>{{element.name}}</h6>
            </div>
            <div class="row plain-element text-start">
              <table class="table-overview">
                {% for key, value in element.items %}
                {% if key != "name" %}
                <tr>
                  <td class="td-category">{{ key }}</td>
                  <td>{{ value | truncatechars:100 }}</td>
                </tr>
                {% endif %}
                {% endfor %}
              </table>
            </div>
            {% endfor %}
          </div>
          <div class=" col col-12 col-sm-12 col-md-12 col-lg-4 plain-element">
            {% for element in meta_3 %}
            <div class="row plain-element text-start">
              <h6>{{element.name}}</h6>
            </div>
            <div class="row plain-element text-start">
              <table class="table-overview">
                {% for key, value in element.items %}
                {% if key != "name" %}
                <tr>
                  <td class="td-category">{{ key }}</td>
                  <td>{{ value | truncatechars:100 }}</td>
                </tr>
                {% endif %}
                {% endfor %}
              </table>
            </div>
            {% endfor %}
          </div>
          {% endif %}
          </div>

        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}